# Generated by Django 2.1.7 on 2019-06-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regex', '0004_remove_regex_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('cadena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regex.Regex')),
            ],
        ),
    ]
