# Generated by Django 2.1.7 on 2019-06-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0003_regex_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regex',
            name='texto',
        ),
    ]
