# Generated by Django 2.1.7 on 2019-03-31 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20190330_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='arch',
        ),
    ]
