# Generated by Django 2.1.7 on 2019-04-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0007_auto_20190411_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='texto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
