# Generated by Django 2.1.7 on 2019-03-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20190329_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='arch',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
