# Generated by Django 2.1.7 on 2019-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_usuario_arch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='arch',
            field=models.FileField(blank=True, default='default.p2', null=True, upload_to=''),
        ),
    ]
