# Generated by Django 2.1.7 on 2019-04-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_remove_usuario_arch'),
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Usuario'),
        ),
    ]
