# Generated by Django 2.1.7 on 2019-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0002_auto_20190602_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='regex',
            name='texto',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
